### ISSUE TITLE
A Javascript uncaught exception error in the desktop app

### ISSUE THREAD

**Issue by marek-lach** [NicolasConstant/sengi#100]
This sometimes happens at launch and prevents the app from running at all, while at other times this error does not occur at all and the app runs normally.

<img width="434" alt="Screenshot 2019-05-18 at 12 30 09" src="https://user-images.githubusercontent.com/45913977/57968368-c7ac5e00-7969-11e9-8e42-41d7b3702b21.png">

**Comment by NicolasConstant** [comment]
Yes it occurs when Sengi already have an open instance, the current workaround is to close all related processes before opening it again.
Thanks for taking the time for reporting it!
