### ISSUE TITLE
Unclear how to get to replies in case of media-only toots

### ISSUE THREAD

**Issue by jumoru** [NicolasConstant/sengi#109]
When a toot only contains a picture and no text at all it isn't very obvious how to "click on it" such that one can see the replies. The only way I've found so far is clicking on the time stamp.

**Comment by NicolasConstant** [comment]
Isn't it the same behavior in MastodonUI? 
Maybe it's missing the status-menu but it will be also implemented soon. :)

**Comment by jumoru** [comment]
Partially :) In the MastodonUI or Mastonaut, for example, you can click / double click on empty space (marked red) to get to the replies.
 
![Bildschirmfoto 2019-06-04 um 11 05 51](https://user-images.githubusercontent.com/27491477/58867024-03f5f300-86ba-11e9-9f2c-6aa358bd0043.png)
![Bildschirmfoto 2019-06-04 um 11 06 57](https://user-images.githubusercontent.com/27491477/58867034-07897a00-86ba-11e9-9782-91618406f75f.png)

**Comment by NicolasConstant** [comment]
Oh ok! I will add some more options to do so. :)
