### ISSUE TITLE
ability to filter out reposts from lists

### ISSUE THREAD

**Issue by wakest** [NicolasConstant/sengi#110]
a quick suggestion. it would be awesome to have a toggle per list to show/hide reposts. I have a list for friends I only know in person and having it only be original content would make it super useful.

**Comment by NicolasConstant** [comment]
Yeah, MastodonUI is providing this too via the column menu.
It shouldn't be a lot of work, I will look to it after releasing polls. :)
Thanks for the suggestion!

**Comment by NicolasConstant** [comment]
will be available in 0.11.0 ;)
