### ISSUE TITLE
Please provide standard application menus in the mac version

### ISSUE THREAD

**Issue by foozmeat** [NicolasConstant/sengi#165]
The current application menu has standard items from other menus added to it. This is not only confusing but may represent a problem for users with accessibility needs. I recommend something like the following for Sengi

* app name
  * About
  * Preferences
  * Hide

* File
  * Close
  * Quit

* Edit
  * Undo
  * redo
  * cut/copy/paste
  * spelling and grammar
  * emoji

* View
  * Zoom In/Out
  * Enter Full Screen
  * Reload

* Window
  * Minimize

* Help

I appreciate your efforts. The client is good otherwise.

**Comment by NicolasConstant** [comment]
Thanks for the insight! I didn't know Apple had guidelines about those. 

I found this official documentation: [Human Interface Guidelines/Menu Bar Menus](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/) that will also help me to fix it in the next release. :)

Thanks for contributing to Sengi!
