### ISSUE TITLE
Accessibility: Select Column without Mouse Click

### ISSUE THREAD

**Issue by tigexplorer** [NicolasConstant/sengi#169]
Hi, 
I've defined to display two columns, the home TL and a list.

How can I switch the focus between the columns without a mouse click?

For accessibility, blind people must be able to select and read a column only with the keyboard.

App-Image 0.16.1
ubuntu 18.04

**Comment by NicolasConstant** [comment]
I was planning to add keyboard shortcuts at some point, especially for the column switching, but reading you make me realize I'll also have to focus the column a make it usable with the keyboard directly.

Thanks for contributing to Sengi!

**Comment by NicolasConstant** [comment]
fixed in 0.17.0!
(use ctrl+right, ctrl+left to switch columns)
