### ISSUE TITLE
Accessibility: Reply Button not in TAB Index

### ISSUE THREAD

**Issue by tigexplorer** [NicolasConstant/sengi#170]
If one make a reply, the tab index contains not the reply button.
So, for example, blind people are unable to reply, while the reply button is not accessible with the keyboard.

App-Image 0.16.1
ubuntu 18.04

**Comment by NicolasConstant** [comment]
Oh good find. I'll have a look to fix those tab indexes. 
But you have a way to send a reply/status without using the button using "Ctrl+Enter". :)

**Comment by NicolasConstant** [comment]
fixed in 0.17.0!
