### ISSUE TITLE
Accessibility: Not able to deselect a list

### ISSUE THREAD

**Issue by tigexplorer** [NicolasConstant/sengi#172]
Via `Mange Account` I'm not able to deselect a list (removing column). Not with a mouse click and not with the space bar when the checkbox is focused.

I've found, that I can TAB to the drop down menu an top of each column, but I can not navigate thru the menu items with the arrow keys, what I expect in a menu. I can TAB thru the items of the menu, but not to the `remove` item on bottom.

App-Image 0.16.1
ubuntu 18.04

**Comment by NicolasConstant** [comment]
Via Manage Account there isn't any way to remove columns (yet).
Like you found, you have to go in the column's menu edition. 

But I found a bug in this edition menu not permitting to TAB them. I've already fix it, and it will be available in the next release. :)

**Comment by NicolasConstant** [comment]
fixed in 0.17.0!
