### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by ahangarha** [NicolasConstant/sengi#181]
For fixing some UI issue, I tried to build the app locally but I failed.

I ran `npm install` which led to some error about vulnerabilities which were fixed by `npm audit fix` and later `npm audit fix --force`. Then I ran `npm run start` and I got a long sequence of error.

I am not sure if I have used a appropriate build procedure. I didn't find any information about how to build for development.

Please help me for this issue and please add some information for others for build process.

tnx

**Comment by NicolasConstant** [comment]
Hi! Thanks for trying Sengi! 

You shouldn't run ```npm audit fix``` as it might break the fragile stack of Angular (I already experienced it, updating Angular isn't trivial and shouldn't be done this way). 

Last time I checked, the vulnerabilities issues weren't in the code that will end in Sengi, and was only part of the dev tooling dependencies (mostly the unit testing framework), so unless it has changed (maybe, I'll do another check this week, and maybe upgrade Angular by the same time) you shouldn't worry about that.

There is a lack of documentation for now, but if you delete your *node_modules* folder, get back the current *package.json* file and run ``` npm install ``` ``` npm start ``` it should be available on localhost:4200. 
If you want to run an electron build, just run ``` npm run electron ```

Please tell me if you run in any other issues!

**Comment by ahangarha** [comment]
I did what you asked. and this is the result:

![image](https://user-images.githubusercontent.com/11241315/66501918-2b7a2380-ead1-11e9-85c3-1c13aecb7d22.png)

on the left, you see the result of `npm install` and on the right, you see the result of `npm start`.

**Comment by NicolasConstant** [comment]
Oh. 
Since it seems to be related to node-sass, I checked my [travis](https://github.com/NicolasConstant/sengi/blob/master/.travis.yml) config file that reminded me that on linux I needed to run ``` npm rebuild node-sass ``` after ``` npm install ``` to make things run smoothly.

It should fix your issue.

**Comment by ahangarha** [comment]
Nope!

![image](https://user-images.githubusercontent.com/11241315/66504702-9417cf00-ead6-11e9-900a-72a44849d9e8.png)

This part or error might help:
![image](https://user-images.githubusercontent.com/11241315/66504766-c0335000-ead6-11e9-9b3d-43f5895c626b.png)

**Comment by ahangarha** [comment]
The issue is found: `Error: Cannot find module 'node-sass'`

I installed the module and done!

**Comment by ahangarha** [comment]
What I don't get is that `node-sass` is already in the `package.json` but it didn't get installed!

**Comment by NicolasConstant** [comment]
Yes I found it in package-lock.json so it's maybe a dependency that wasn't retrieved properly, which is odd. 

If this occur too often, I will add this step in my (future) documentation...

**Comment by ahangarha** [comment]
I tried again on a different installation of GNU/Linux. I am facing with the same issue. I cannot compile

**Comment by ahangarha** [comment]
I installed node-sass manually using:

`npm install node-sass`

though I still get these errors:
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/sengi2/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.0-29-generic
gyp ERR! command "/usr/bin/node" "/tmp/sengi2/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /tmp/sengi2/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```
But at least now `npm start` works

I am not sure if this is the reason, but it seems `node-sass` is not in dependencies in `package.json`

**Comment by NicolasConstant** [comment]
There is something strange here (since I'm building Sengi via CI/CD on all platforms). 

Looking to the [Travis build steps](https://github.com/NicolasConstant/sengi/blob/master/.travis.yml) it seems we need to "rebuild" node-sass to make it work, maybe it's related?

**Comment by NicolasConstant** [comment]
I just pulled the current master on Ubuntu 19.10, and build it properly without any error. 
What version of node are you using? On Windows I've seen some issues on Angular 7 with Node 12, I'm using node 10 on my side (on Win and Ubuntu), maybe that's the issue?

**Comment by ahangarha** [comment]
```
$ nodejs --version
v12.14.1
```

**Comment by NicolasConstant** [comment]
Ok that was the issue! 
It seems Angular 8 fixes this issue (it's event mandatory to be on node v12 apparently), I'll try to upgrade Sengi to this last version very soon. 

I have created a [dedicated page](https://github.com/NicolasConstant/sengi/wiki/How-to-Build) on the wiki so that this dependency is clearly stated. :)

**Comment by ahangarha** [comment]
This is great

Thanks
