### ISSUE TITLE
ALT key malfunction

### ISSUE THREAD

**Issue by ahangarha** [NicolasConstant/sengi#183]
App is too sensitive for pressing ALT key. When I try to push a shortkey combination like ALT+SHIFT for switching between keyboard layouts, the menu bar appears which is not what I wanted. I think the trigger is wrong.

OS: Kubuntu 19.04
I am using the app not the browser version. I have Firefox on my system
Sengi version: 0.18.0

**Comment by NicolasConstant** [comment]
It's the default behavior/implementation of electron (https://github.com/electron/electron/blob/ead8f2bbcd2e4f83540cc994791e7aa9a96a32ae/docs/api/browser-window.md section autoHideMenuBar ). 

I will update Sengi to the last version of electron to see if it change this behavior.

**Comment by NicolasConstant** [comment]
On the last version of Sengi were are now on Electron 8, did this version solve your issue?

**Comment by ahangarha** [comment]
I am still running older version as I was not able to update my custom version with you. But I will check and tell you

**Comment by NicolasConstant** [comment]
Thanks! :)

**Comment by ahangarha** [comment]
I confirm that pressing ALT key as combination with SHIFT does not activate the menu. The menu gets activated only if ALT key be pressed alone.

Thanks

**Comment by NicolasConstant** [comment]
That's great to hear! Thanks for checking it out!
