### ISSUE TITLE
Add RTL (bidi) support

### ISSUE THREAD

**Issue by ahangarha** [NicolasConstant/sengi#186]
## Description

The app forcefully shows toots in LTR direction. This, not only aligns RTL text in wrong side but also if the text be mixed RTL/LTR, it doesn't render it in proper order.

![image](https://user-images.githubusercontent.com/11241315/66706297-b4959280-ed3d-11e9-9609-09262ad91bda.png)
The wrong rendering

![image](https://user-images.githubusercontent.com/11241315/66706325-eeff2f80-ed3d-11e9-9be7-471cb47231f6.png)
The correct rendering

I have opened the same [issue on whalebird](https://github.com/h3poteto/whalebird-desktop/issues/1058) repo as well.

You may check this toot as reference: https://mastodon.host/@ahangarha/102934203632874455

**Comment by NicolasConstant** [comment]
Right. In fact that might mean that we have to do this on all the user editable texts: 
- [ ] status text
- [ ] user name (in all interfaces)
- [ ] user profile description
- [ ] user profile fields
(maybe more that I don't see right now)

Since you already worked on the codebase, is it something you would be interested to do?

**Comment by ahangarha** [comment]
I have been assigned to solve this on whalebird. I have tried to motivated
some other friends to work on this issue here. If they don't, I will work
on it for sure. I would prefer it be done by others so they gain knowledge
of this and can apply it on other projects

در تاریخ یکشنبه ۱۳ اکتبر ۲۰۱۹،‏ ۸:۰۳ Nicolas Constant <
notifications@github.com> نوشت:

**Comment by ahangarha** [comment]
I have found a good way to address this issue. Hopefully today I will fix it.
