### ISSUE TITLE
Slow Mode setting

### ISSUE THREAD

**Issue by melissasage** [NicolasConstant/sengi#204]
Mastodon at least has a Slow Mode setting that won't fetch new statuses until manually requested by the user, instead just displaying a count at the top. This is really useful since some of my timelines move very fast- and in some cases I might, for example, boost a status I didn't mean to because the timeline shifted. I don't know if this is exposed to the API- if so it'd be great if Sengi respected the existing Slow Mode setting, or else just the ability to enable it client-side.

**Comment by NicolasConstant** [comment]
Sengi already doesn't feed the TL when you're scrolling it. But a Slow Mode would indeed be a nice addition too. :)
