### ISSUE TITLE
Windows login error

### ISSUE THREAD

**Issue by melissasage** [NicolasConstant/sengi#208]
I downloaded the official Windows installer and I'm getting an error when I log in that seems to be the same one as [#198](https://github.com/NicolasConstant/sengi/issues/198). The recommended fix of clearing account data and trying again didn't fix it, either.

I tried to open it with PowerShell and get you some logs for further inspection but that didn't work; if you have a suggestion for getting you useful logs I'll happily try it.

**Comment by NicolasConstant** [comment]
Can you try to uninstall/reinstall Sengi to see if it helps? 
I not, does the [web version](https://nicolasconstant.github.io/sengi/) of sengi is working for you?

**Comment by NicolasConstant** [comment]
Closed due to inactivity. Please comment if you still have issues. :)
