### ISSUE TITLE
Redraft, removed line breaks and put all the text in one paragraph

### ISSUE THREAD

**Issue by ahangarha** [NicolasConstant/sengi#224]
As mentioned in title, by clicking "delete and redraft" for a toot, all the line breaks in the body of the toot gets removed. So all the content comes together in one long paragraph.

Tested on v.0.20.0

**Comment by NicolasConstant** [comment]
Redraft is effectively still a bit broken now, I also have some issue with the account names when there are from other instances. 
I'll try to refine this. :)

**Comment by stom79** [comment]
I got that issue too. Mastodon uses a different way to represent these accounts. I solved it with a different regex to extract them. Here is my fix: https://framagit.org/tom79/fedilab/-/blob/develop/app/src/main/java/app/fedilab/android/activities/TootActivity.java#L3204
