### ISSUE TITLE
Trim instance hostname 

### ISSUE THREAD

**Issue by stom79** [NicolasConstant/sengi#225]
A really small fix, it could be nice to trim the instance name when logging in. Especially when devices automatically add a blank with auto-complete. 
![Screenshot_20200223_201409](https://user-images.githubusercontent.com/30171182/75118329-7a3bea80-5679-11ea-8694-fc1379afdb8c.jpg)

**Comment by NicolasConstant** [comment]
Oh good one. Will fix this rapidly.
