### ISSUE TITLE
Toot editor's contents reset when navigated away

### ISSUE THREAD

**Issue by cadadr** [NicolasConstant/sengi#235]
Steps:

1. start composing a toot
2. navigate to e.g. the profile view, clicking on the column on the right
3. go back to the toot editor
4. observe the editor is empty, toot was lost

Expected:

Preserve toot editor's contents unless manually cleared or toot posted.

OS & Version:
Debian Buster, Cinnamon Desktop, Sengi 0.20.1.563 (AppImage release).

**Comment by NicolasConstant** [comment]
Yeah, it's an improvement I was thinking about since a long time, thanks for bringing it here!
