### ISSUE TITLE
Return on the top of timeline add all missing statuses

### ISSUE THREAD

**Issue by c-chell** [NicolasConstant/sengi#241]
When I go down in the timeline (just to pause the scrolling and continue after being away of the interface), when I reach the top of the (old) timeline, all newer statuses loaded at the same time.
It's annoying because I have to go down to find (no tag or indication where it was) where I was to read all the new statuses added.

On the default interface of Mastodon, the newer statuses loaded on the top but the list stay on the same suatuses (I don't know if it's a clear explanation).

Version 0.22.0

**Comment by NicolasConstant** [comment]
Hi!
I didn't use the default mastodon interface since a while, but I will have a look to see this behavior. 
If possible I'll add an option to meet this other behavior. (the current one is "on purpose") 

Thanks for contributing to Sengi!
