### ISSUE TITLE
Toot text is not displayed when "href" is included as a text in the toot

### ISSUE THREAD

**Issue by eai04191** [NicolasConstant/sengi#276]
![image](https://user-images.githubusercontent.com/3516343/80941778-4a018c80-8e1e-11ea-8ba2-b14f60cb868e.png)
![image](https://user-images.githubusercontent.com/3516343/80941773-47069c00-8e1e-11ea-8c8c-9363b3af0e56.png)
![image](https://user-images.githubusercontent.com/3516343/80941806-55ed4e80-8e1e-11ea-9fcf-3751f9f79e64.png)

https://stellaria.network/@Eai/104108832391053628

**Comment by NicolasConstant** [comment]
Oh my parsing strategy seems to be a bit candid on this side. I'll fix it very soon!

Thanks for contributing to Sengi! :)
