### ISSUE TITLE
Add a way to see followers/follows of an account

### ISSUE THREAD

**Issue by NicolasConstant** [NicolasConstant/sengi#292]

**Comment by RedSnt** [comment]
I'd love to see this feature implemented. I like to keep everything organized using lists, so if I can't access my "following" list it can easily be hard to add accounts to certain lists. Luckily I can just use the regular vanilla web version of Mastodon to do so of course, but it would be nice if it was accessible through Sengi.

**Comment by NicolasConstant** [comment]
This feature is implemented. 😉
You can click on "Following" and "Followers" when looking at any profile, it will show you the list.

What is missing tho is the capability to add an account to a list from those UI, that's something that would be useful indeed.
