### ISSUE TITLE
Out of Memory caused by multiple long URLs in post form

### ISSUE THREAD

**Issue by eai04191** [NicolasConstant/sengi#303]
##  Description
https://i.imgur.com/1wJR8oy.mp4

## Expected Behavior
Chrome doesn't crash

## Actual Behavior
Chrome crashes in Out of Memory

## Steps to Reproduce
1. Open sengi
2. Paste long url ([like this](https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%AB%E3%83%B3%E8%88%AA%E7%A9%BA191%E4%BE%BF%E5%A2%9C%E8%90%BD%E4%BA%8B%E6%95%85)) in post form.
3. Paste it several times
4. It Freeze. In the case of this URL, it happens the fourth time.
5. Chrome crash in Out of Memory

## Environment
* Version used: Sengi 0.30.0
* Browser Name and version: Chrome 83.0.4103.116 (Windows 64bit)

**Comment by NicolasConstant** [comment]
Thanks for your bug report! I found the issue very easily and it will be fixed in next release. :)
