### ISSUE TITLE
The rule that sets the number of characters in the URL to 22 (23) does not work if there is a character before the URL

### ISSUE THREAD

**Issue by eai04191** [NicolasConstant/sengi#308]
![2020-08-09_07-58-32_chrome](https://user-images.githubusercontent.com/3516343/89721259-7d077d80-da16-11ea-97a5-3036409a1718.png)
![2020-08-09_07-58-39_chrome](https://user-images.githubusercontent.com/3516343/89721260-7da01400-da16-11ea-98c0-40f783bc8541.png)

It must have the same behavior as Mastodon's Web UI.

**Comment by NicolasConstant** [comment]
Thanks for letting me know!
