### ISSUE TITLE
sengi does not give a noopener when opening a link attached to a post

### ISSUE THREAD

**Issue by eai04191** [NicolasConstant/sengi#309]
Demo: https://stellaria.network/@Eai/104726679770443277

Video: https://i.imgur.com/wzMWBWG.mp4

As you know, this is a security risk.

**Comment by NicolasConstant** [comment]
Yes, I will have a second look on this one.

**Comment by eai04191** [comment]
Goooood!
link is now a simple a-element, which makes it much easier to handle. (Now I can middle-click!)
Sengi is my most favorite client.
Please keep it up!

**Comment by NicolasConstant** [comment]
Happy you like it!
I should have rework this part of the code sooner, it's much better now. 🙂
