### ISSUE TITLE
Follow Requests

### ISSUE THREAD

**Issue by tobbsn** [NicolasConstant/sengi#322]
I can't find a way to manage follow requests.

One of my accounts is locked, and when I get a new follow request, I have to use the web interface or another app to handle it. 
I also can't find the notification in my notifications stream, although I get the blinking profile pic and the notification sound - But there is no new notification in the stream.

**Comment by NicolasConstant** [comment]
Hi! 
Yes locked account/follow requests aren't supported yet, and that might explain the glitches you're experimenting. 
But I will work on it very soon. 🙂 

Thanks for contributing to Sengi!

**Comment by NicolasConstant** [comment]
Sengi is now supporting follow requests in the notifications!
