### ISSUE TITLE
Logo does not appear when running from appimage

### ISSUE THREAD

**Issue by apothan** [NicolasConstant/sengi#324]
**How to reproduce the issue**

- Download Sengi-0.31.1-linux.appimage
- Run: chmod +x Sengi-0.31.1-linux.appimage
- Run: ./Sengi-0.31.1-linux.appimage

**The expected behavior**

The logo should appear in the top left of the window Sengi runs in and the logo should appear in the task manager also.

**Screenshot**

![sengi_issue](https://user-images.githubusercontent.com/4775046/94279165-be49e300-ff19-11ea-8c9c-725d307834fd.png)

**OS**

Ubuntu 20.04, KDE

**The Sengi version**

Sengi-0.31.1-linux.appimage

**Comment by apothan** [comment]
It seems to be an issue many people have.

These guys:
https://github.com/electron-userland/electron-builder/issues/2269

Proposed this solution:
```
win = new BrowserWindow({
   ...
   icon: path.join(__dirname, '/icon/Icon-512x512.png')
})
```

I am not sure how to build an appimage.

**Comment by NicolasConstant** [comment]
It seems to be an electron issue indeed. 🙂 
I'll do some tests on my side, thanks for contributing to Sengi!

**Comment by NicolasConstant** [comment]
It was a bit more work than I would have imagined, but I think I finally have something that is working as expected. 

Please find the prerelease here: https://github.com/NicolasConstant/sengi/releases/tag/0.32.1 so that you can check if it's displaying properly on your side. 🙂

**Comment by NicolasConstant** [comment]
It should be fixed now, download the last release and if not let me know.
