### ISSUE TITLE
Tag Docker images

### ISSUE THREAD

**Issue by mxmehl** [NicolasConstant/sengi#325]
Just a minor request: could you please tag the docker images according to their releases? Currently, there is only `latest`, and there is no way to pin to a specific version.

You could configure automated builds in Docker Hub with the following patterns:

```
Tag       /^[0-9.]+$/     release-{sourceref}
Branch    master          latest
```

If you need some assistance, I can gladly help :)

**Comment by NicolasConstant** [comment]
Yes, it's something that would definitively need an improvement. 
I have made some tests for supporting ARM architecture and it would bring the tags in the same time. 🙂

**Comment by NicolasConstant** [comment]
I've added the patterns first, so we now have the proper tags on docker images!

**Comment by mxmehl** [comment]
Thank you, now [upgrading is a bliss](https://git.fsfe.org/fsfe-system-hackers/sengi/commit/4f5b383895f95eca64b0b9e213e10f402a30edeb) for me :)
