### ISSUE TITLE
Error on attachment upload

### ISSUE THREAD

**Issue by mxmehl** [NicolasConstant/sengi#331]
Since a few days, I keep getting errors when trying to attach pictures and other material to my posts

```
Http failure response for https://mastodon.social/api/v1/media: 422 OK
```

I am using sengi as a web service.

**Comment by NicolasConstant** [comment]
Oh this is odd. 
I just tried with my @sengi_app@mastodon.social account and it works fine. Can you remove your account and relog to the server? Maybe there is something wrong with your authentication token or so.

**Comment by mxmehl** [comment]
OK, for some weird reason, the error only appears when using Rambox, even after cleaning all local data from inside Sengi. I will try to pin down the issue.

**Comment by NicolasConstant** [comment]
Closing, please comment if you have more info and if there is something doable on Sengi's part to solve your issue. 🙂
