### ISSUE TITLE
[feature request] Add option to open profile in web browser

### ISSUE THREAD

**Issue by stragu** [NicolasConstant/sengi#334]
Currently, when looking at a profile (for example when someone new follows you), it is not possible to easily open their profile in a web browser to see more than what has reached the instance. It is a common thing to do in order to determine if we are happy interacting with that person.

Could there be an easy link to open a profile in a browser, for example an extra item in the three-dot menu that says "View in browser"?

**Comment by NicolasConstant** [comment]
You can left-click on the fediverse's handle in the account panel to open it in a browser. 🙂
You can also middle-click on the avatar and the fediverse's handle anywhere in the app. 

I can add an option in the three-dot menu but my guess is people will probably use the aforementioned way to do it.

**Comment by stragu** [comment]
Oh wow how did I miss that!?
Sorry for the noise, and thanks for the quick reply :)
