### ISSUE TITLE
Profile info needs to have forced wrapping of text

### ISSUE THREAD

**Issue by wakest** [NicolasConstant/sengi#34]
easiest to explain with a little video

![screen recording 2019-02-23 at 4 13 20 pm 2019-02-23 16_17_28](https://user-images.githubusercontent.com/7890201/53292345-9ebf6700-3786-11e9-8e2f-be2f85cdb55e.gif)

**Comment by NicolasConstant** [comment]
Oh, didn't know this one, thanks! 
I'll fix it in 0.2.
