### ISSUE TITLE
Removal of favorites seems buggy

### ISSUE THREAD

**Issue by Silmathoron** [NicolasConstant/sengi#344]
I've noticed it for a while but never bothered enough to open an issue but since I started one today, I might as well do this one too!
I'm used to use favs as a way to tell somebody I liked the post but I remove it immediately unless I really want to find it again later (in which case I keep it as some kind of "super bookmark).

**The bug**
It seems that immediately unfaving a post does not work in Sengi: the start indeed disappears from the post as expected, but... it's still in the favorites.

**A fun how to reproduce with a bonus**
Even better, try to find a post that appears twice on your interface: fav it, unfav it on the same post... the star is still yellow on the second one. Unfav that second post and *tadaa*, post is now correctly gone from your favorites.

This happens on all instances I use, on Sengi 1.0.2 and in previous releases.

**Comment by NicolasConstant** [comment]
Is it on Pleroma or Mastodon instances?

**Comment by Silmathoron** [comment]
Mastodon, unfortunately I'm having a hard time finding nice Pleroma instances to try it out...

**Comment by NicolasConstant** [comment]
Ok thanks! I'll look to reproduce this on my side.

**Comment by Silmathoron** [comment]
@NicolasConstant did you manage to reproduce the bug?
Sorry to up the thread but dealing with it every day is getting a bit annoying, so if it's only on my install, I would appreciate some tips about stuff I could do to find where the issue comes from ^^"

**Comment by NicolasConstant** [comment]
Hello, I haven't take the time yet (keep in mind I do this on my free time 😉), I'll try to take a look at it in the following days/weeks.

**Comment by Silmathoron** [comment]
Maybe I mis-phrased this: I understand that you have only so much time you can spend on this, which is why I meant to say that if there are ways in which I can gather some logs or things that will save you time to investigate the issue, let me know

**Comment by NicolasConstant** [comment]
I tried to reproduce it on my side.. seems to work as expected:

https://user-images.githubusercontent.com/5437247/110891604-5832fb80-82c0-11eb-8b4f-de4b20753084.mp4

can you describe exactly the workflow that isn't working? How are you checking that the post isn't faved anymore?

**Comment by Silmathoron** [comment]
I pick a random post on my home timeline, fav and unfav, just like you did, but then I check it in the favorite list and it's still marked as favorite.
Checking on the webapp or on my phone app also shows that the post is still in my favorites.

Going to the favorite list on Sengi, then unfavoring works, however.

**Comment by NicolasConstant** [comment]
I think I found the issues, normally it's fixed in 1.1.1. 😉
