### ISSUE TITLE
Non legible font in attachment window

### ISSUE THREAD

**Issue by fooluke** [NicolasConstant/sengi#350]
![sengi_bug](https://user-images.githubusercontent.com/77808749/105411163-ca1c8c00-5c11-11eb-9462-1e2c90c5bd2b.png)
when I try to attach an image the font in the window is not readable

Sengi version: 1.0.3

Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.9.16-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-7020U CPU @ 2.30GHz
Memory: 3.8 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by NicolasConstant** [comment]
Hi! 
Since you're using the Electron build, can you tell me what build did you take (snap, AppImage, deb, etc?) and when did you download/install it? 
Also are you using any custom fonts/localization settings/etc?

**Comment by fooluke** [comment]
Snap, and if i remember i've downloaded it in wednesday 20 jan. Fonts are all from distro standard, no change. My language is Brasil Portuguese that i set in installation.

**Comment by NicolasConstant** [comment]
Ok thanks for your detailed information!

**Comment by ahangarha** [comment]
Many snap apps become like this. I don't know why. I have stopped using snap.

**Comment by erik-sk** [comment]
I am having the same issue. Installed with snap two days ago. Version number is 1.1.5 . I am on Manjaro Linux using xfce desktop. I feel like this is just a font issue, but can't begin to guess which it would be.

**Comment by erik-sk** [comment]
Works in the appimage, but I have to add "--no-sandbox" in the execute command to avoid a "GPU process isn't usable" error.

**Comment by NicolasConstant** [comment]
The last release (and new Electron version) seems to have fixed this; https://github.com/NicolasConstant/sengi-electron/releases/tag/v1.5.5
