### ISSUE TITLE
Tags showing as broken html

### ISSUE THREAD

**Issue by PrivacyDragon** [NicolasConstant/sengi#357]
Tags are sometimes just working perfectly well, but sometimes not.
I use Sengi 1.0.3 and I use two accounts.
Mostly this bug is on the left bar only.

Tags will show up like this:
`MicroFiction" title="#MicroFiction" target="_blank" rel="noopener noreferrer">#MicroFiction TootFic" title="#TootFic" target="_blank" rel="noopener noreferrer">#TootFic SmallStories" title="#SmallStories" target="_blank" rel="noopener noreferrer">#SmallStories`

I have really no idea how this is possible and on another bar, with my other account this problem does not show up.
And I have already checked if it is something about the instance, but that is not the case

**Comment by NicolasConstant** [comment]
Yes I've created parsers to support most of the Fediverse software but some might not be supported by the current implementation. 

Thanks for the sample but can you provide me the related status/software so that I can add a particular unit test for this illustration?
