### ISSUE TITLE
Post button should use general language

### ISSUE THREAD

**Issue by wakest** [NicolasConstant/sengi#36]
Yes Mastodon defaults to calling them Toots, but Pleroma does not and I know it annoys many folks. I have not heard yet a good argument why this button in any software should not be labeled Post. It can be a fun thing to customize but it should default to language everyone understands and not something new people need to learn new vocabulary for. 
<img width="331" alt="screen shot 2019-02-23 at 5 28 57 pm" src="https://user-images.githubusercontent.com/7890201/53292932-8e13ee80-3790-11e9-9e83-cd03a4c2c75c.png">

**Comment by NicolasConstant** [comment]
I agree. 
It's a first draw result that lasted after that (I also have some mastodonish named variables in the code, didn't get rid of all of them yet).

Lets go for POST then. :) 
Thanks for pointing that out!
