### ISSUE TITLE
Question: Difference between "enhancement" and "feature request" labels

### ISSUE THREAD

**Issue by mmahmoudian** [NicolasConstant/sengi#377]
While going through the issues of this repo, I realized there are two labels used that in my head mean the same thing: "enhancement" and "feature request"
</br>

![image](https://user-images.githubusercontent.com/390889/118125544-d1091d80-b3ff-11eb-8273-d8faa3308c8f.png)

**Comment by NicolasConstant** [comment]
Yeah the descriptions might be a little off, but for me it's just the same thing with this main difference; 
* **enhancement** is based on an already present feature
* **feature request** is a new (or different enough) feature
