### ISSUE TITLE
[Feature Request] Tray icon and minimize to tray

### ISSUE THREAD

**Issue by mmahmoudian** [NicolasConstant/sengi#382]
One of the features that I really miss in Sengi is the ability to minimize to tray. At the moment I have to keep it open and clutter my workspace. I usually hate to compare softwares, but perhaps this is a constructive one. What Whalebird does is :

![image](https://user-images.githubusercontent.com/390889/120625051-f969c200-c469-11eb-834b-b3514e131d53.png)

**Comment by Salastil** [comment]
You can get this kind of functionality using nativefier which is an electron wrapping program. 

`nativefier http://192.168.1.0:8090/ --name Sengi --user-agent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0" --single-instance --tray --internal-urls "(.*?)firstdomain.tld/oauth|secondaryaccountdomain.tld/oauth(.*?)"`

There are other flags for nativefier but this is what I was running with. --single instance is self explanatory, --tray gives you the function you want, --internal-urls allows the electron window to leave the Sengi interface to the oauth function page so you can log in. Each successive account you want needs to be whitelisted by that internal-urls bit, or you could just wildcard everything around the "oauth" portion of the url I suppose. The only downside is that nativefier bitches about the "app" being outdated after a period of time and you have to build again from scratch as there doesn't seem to be an "update" function for existing applications built from it. That should give you a basic functional build, anything further you would have to check the documentation:
https://github.com/nativefier/nativefier

**Comment by stemy2** [comment]
The nativefier method seems pretty complicated, especially for non-nerdy users.

**Comment by y0himba** [comment]
Not sure of the etiquette here, but I would also like to see this feature, native. I am currently using DisplayFusion Pro to minimize to tray.
