### ISSUE TITLE
login to Pleroma accounts result in Error 0

### ISSUE THREAD

**Issue by wakest** [NicolasConstant/sengi#39]
I get "0: Unknown Error" when I tried to log into either of the Pleroma accounts I have:
https://hub.spaz.org and https://cathoderay.tube

**Comment by NicolasConstant** [comment]
Oh that's strange, the only account I have is on https://pleroma.site, and it's working (tested right now). 
I'll create some test accounts on those ones to see what's going on.

**Comment by NicolasConstant** [comment]
https://twinkaga.in was also reported as problematic. Strange thing, all seems to be on the same version. 

All those are closed to new registrations, if you have an instance that isn't working and still opened to new registrations, please share it will be easier for me to debug.

**Comment by wakest** [comment]
I can just change my passwords on accounts I have on both https://hub.spaz.org and https://cathoderay.tube and let you use them to test. They are both just test accounts anyway basically

**Comment by NicolasConstant** [comment]
In last resort it could work, thanks! :) 
But I have news, maybe it won't be necessary:

twinkaga.in's admin kindly gave me an account for testing, and I couldn't reproduce the issue, and the initial person that had an issue with this instance now can't reproduce on his side either. 

Maybe Pleroma had an update? Can you retry to log from https://hub.spaz.org and  https://cathoderay.tube to see if the issue is still present? And if so, can you open your console (right click/Inspect/console) and send me the content? 

It seems this is very difficult to reproduce... :/

**Comment by wakest** [comment]
they both have the same issue still:

<img width="977" alt="screen shot 2019-03-03 at 3 47 00 pm" src="https://user-images.githubusercontent.com/7890201/53702352-9e991a00-3dcb-11e9-9b84-2c1748ad7862.png">

**Comment by NicolasConstant** [comment]
Oh, that's interesting! So those instances don't accept creating a new app, I'll have a look to see if I can solve this on my side. 
Thanks!

**Comment by NicolasConstant** [comment]
So, obviously it's a CORS issue, so mostly a server issue, but I wanted to understand _why_ it was occurring with Sengi and not Pleroma-FE. Here are my findings: 

With Pleroma-FE, the response headers are the following:
![image](https://user-images.githubusercontent.com/5437247/53703025-1d498380-3ddb-11e9-919e-92d630721e3b.png)

But with Sengi, we are getting this back: 
![image](https://user-images.githubusercontent.com/5437247/53703028-305c5380-3ddb-11e9-961b-fa68ce130db4.png)

Obviously, both are wrongly formatted headers, maybe by a wrongly configured nginx config file, and even if the first one seems to be accepted by the browser, it's not the case for the second one.
And... I can't do anything about that. :( 

I will check with Pleroma devs to make sure their installation procedure aren't adding more headers than needed that might explain why so many Plemora instances aren't behaving correctly. 
And also will try to handle this particular error in Sengi to display a better error message.
