### ISSUE TITLE
Emoji viewer fails on Mastodon instance with AUTHORIZED_FETCH

### ISSUE THREAD

**Issue by sungo** [NicolasConstant/sengi#391]
When AUTHORIZED_FETCH is set on a Mastodon instance, the custom emoji endpoint requires authentication. Currently, on such an instance, Sengi fails to retrieve custom emoji and displays an error message.

In theory, one is able to access that custom emoji endpoint by passing along the same credentials used in other API calls.

**Comment by trondd555** [comment]
I noticed this also as gotosocial requires authorized access to custom emojis.  Now the Mastodon instance I am on also requires it.
