### ISSUE TITLE
Can't add instance knallgrøn.space

### ISSUE THREAD

**Issue by librewarrior** [NicolasConstant/sengi#397]
I have added sites like snabelen.no and sjåpåmeg.space to sengi and those works. However, when trying to add the site knallgrøn.space, I get the error message: 

Submit
Http failure response for https://xn--knallgrn-c5a.space/api/v1/apps: 504 Gateway Timeout

I am currently logged in on knallgrøn.space in the browser so I know the server is communicating. It is running the hometown fork if that is relevant by any chance.

**Comment by NicolasConstant** [comment]
Hi!
It's a CORS issue: 
![image](https://user-images.githubusercontent.com/5437247/141891233-a576c95d-03e4-436c-8ca1-bddb8cfa80e8.png)

Unfortunately it's a very common issue and is related to how browsers works and the way the instance is set, to fix it please reach your instance's admin to add the `Access-Control-Allow-Origin: *` header in his instance configuration.

Another solution would be [this workaround](https://github.com/NicolasConstant/sengi/issues/332#issuecomment-751310544) but fixing the instance's configuration would be way better of course.
