### ISSUE TITLE
Filters do not work

### ISSUE THREAD

**Issue by PrivacyDragon** [NicolasConstant/sengi#414]
I recently set up some filters in my Mastodon account, but Sengi does not seem to apply those filters.

**Comment by NicolasConstant** [comment]
Hi! 
Can you describe what actions you performed, what was the result and what was excepted?

**Comment by NicolasConstant** [comment]
Sengi provides it's own filters, so yes, other settings from other clients will not work.

I wasn't aware there was accounts filters now (there wasn't when I developed the filters functionalities), I will have a look to it.

**Comment by ThatGeoGuy** [comment]
Yeah, even Sengi's own filters don't work. For example, I tried to filter `monsterdon;#Monsterdon` to filter out that specific hashtag, and it doesn't work for toots that end on that string. 

Either way, it would be nice to be able to filter toots a bit better. Sengi does seem to have some edge case here, even if it's all built in filters and not Mastodon account filters.

**Comment by halnine** [comment]
Update, since this issue is rather old: the issue still exists.

**Comment by markwalkom** [comment]
I was having issues with this until I figured out the format;
```
term;anotherterm
```
So the semi-colon is the separator. It doesn't seem to like non-alphanumerics, like `#` or even `.`.

**Comment by FlitPix** [comment]
Adding new filters manually to Sengi is not ideal, especially when new relevant topics come about fairly often (game spoilers, etc). It also means I have to add all of my filters twice if I want to continue using Sengi as my daily driver. Please add this!

**Comment by NicolasConstant** [comment]
server side filters will be available next release!
