### ISSUE TITLE
No application icon in sengi 1.1.5 appimage

### ISSUE THREAD

**Issue by ghost** [NicolasConstant/sengi#421]
Attached below are some screenshots of the missing icon.

![image](https://user-images.githubusercontent.com/58090734/160307048-704cf2a9-19d7-4e00-a449-33930002cb68.png) ![image](https://user-images.githubusercontent.com/58090734/160307036-bc5c191c-ed13-401a-b80c-46425cb65e70.png)

**Comment by NicolasConstant** [comment]
That's something I've fixed in the past (#324) can you give me more information on your OS/Desktop settings/etc?

**Comment by Siinamon** [comment]
I am running a stock, unmodified KDE Plasma 5.24.3 in Gentoo. I have tried it on my laptop with the same settings but in Arch, and also get a missing icon.

**Comment by NicolasConstant** [comment]
closing due to rehosting the Electron build in another repository
