### ISSUE TITLE
Http failure response when login on tabletop.social

### ISSUE THREAD

**Issue by vylion** [NicolasConstant/sengi#423]
I get this error when trying to login on tabletop.social:

![image](https://user-images.githubusercontent.com/13038852/162647313-81b52695-db8f-4264-825a-f29929e40242.png)

From the error I'm guessing it may be related to the fact that tabletop.social is https-only? Loging in to other instances like octodon.social works for me.

I downloaded the exe for Windows, I'm running it under Windows 10 64-bit. Trying the [live web app](https://nicolasconstant.github.io/sengi/#) also gives me the same error.

**Comment by NicolasConstant** [comment]
Hi! 
It's an instance configuration issue. Please check #397 for details and workaround.
