### ISSUE TITLE
Suggestion: small UI improvements

### ISSUE THREAD

**Issue by colognella** [NicolasConstant/sengi#429]
I'd like to suggest 2 small UI changes in the Sengi Desktop App (1.1.5, Windows, MacOS):

1. When you click on the search icon, I'd expect to use the search bar, just by typing my search phrase. It would be nice to have the focus in the search field. Instead, when typing, you seem to jump into a new post field. 
2. After opening a single post, search, etc. in a column, you can close this view by clicking on (x) icon. It would be very nice if closing by keyboard (ESC) would be possible. 

Just a humble suggestion, thanks for your great work!

**Comment by ericfreyss** [comment]
Hello ! The focus thing when you click on the search icon is really making things difficult on a daily basis: the usual behaviour in most UIs is to set the focus on the expected function when you make it appear.

**Comment by colognella** [comment]
Hi, thanks! So what would be the expected function when I click on the search icon? I'd just like to understand.

**Comment by ericfreyss** [comment]
Have the focus set in the search box, such as when you start typing the texte goes into the search box. Currently you need to click on the search icon, and then click in the search box before typing.

**Comment by NicolasConstant** [comment]
fixed, will be available on next release!
(you'll need double "esc" in some cases : one to unfocus, one to close the panel)
