### ISSUE TITLE
linux sha256sum?

### ISSUE THREAD

**Issue by the-rocinante** [NicolasConstant/sengi#441]
I notice there's a checksum file for the Windows and Mac version, but not one for Linux (.deb). It would be good to have some consistency and not leave us Free Software folks behind.

Also having a GPG signature and signing key seems like a pretty standard best practice to adopt.

Hopefully you can prioritize that for future releases, or as an update for the current.

**Comment by sid-the-sloth** [comment]
Would also be nice to have a sha256 checksum file  for the Linux AppImage bundle, too.

**Comment by sid-the-sloth** [comment]
A good example are projects like VSCodium and Mdview, here on github.

**Comment by NicolasConstant** [comment]
closing the issue here since it's an Electron related issue
