### ISSUE TITLE
[CLOSED] Http failure response...on deb installed version not a browser issue!

### ISSUE THREAD

**Issue by bornagainpenguin** [NicolasConstant/sengi#443]
Hi!  Trying to use the client I installed from the deb offered is giving me this message:

Http failure response for https://bornagainenguin@fosstodon.org/api/v1/apps: 504 Gateway Timeout

I have seen other posts about login issues and I have seen it responded to with it being a browser issue.  This is not that.  This is using the Sengi version: 1.1.5 deb installed on a Ubuntu-Mate 20.04.4 LTS system.

I am wondering if perhaps I am not inputting the correct information?  Any assistance would be appreciated!

[Screenshot at 2022-07-13 09-51-50](https://user-images.githubusercontent.com/82099949/178764109-65235228-8025-4724-8ff9-2d1f836ed977.png)
.

**Comment by bornagainpenguin** [comment]
Further reading of the issues like this being reported has me losing faith in the app itself.  Everything seems to be CORS related.  I thought by installing the deb I was installing an application, not an element webapp that no one seems to understand what it is doing.  Going to remove this and go back to something that works.

Thanks any way.

**Comment by NicolasConstant** [comment]
>  I thought by installing the deb I was installing an application, not an element webapp that no one seems to understand what it is doing.

Sengi is an alternative front-end above all - technically a PWA - I only provide an electron build for those how like it. 

If you have CORS issues, any alternative front-end will fail, it's not an app issue, it's an instance misconfiguration.
