### ISSUE TITLE
Random spawned login screen

### ISSUE THREAD

**Issue by Salastil** [NicolasConstant/sengi#446]
![1661975509](https://user-images.githubusercontent.com/46979341/187772371-b40cea09-8f1b-4d80-866d-976942c51442.png)

This white and blue login screen randomly spawns in, I've had this before but never bothered to scrutinize it too much, maybe third or forth time I've seen it when running Sengi since Dec 2020. I have zero idea what specific instance or software is causing it to spawn. I have Sengi wrapped in an electron browser via nativefier so I could drop it to the system tray when not in use, I don't see how this would affect it more than any other Chromium based browser though, so I suspect that just running Sengi in any browser will likely spawn this login screen. xprop confirms that the login screen did indeed come from this, using developer tools to try inspecting the spawned window failed and I saw nothing else about it in the tools. I saw https://qip.wang/ in the error logs and the color scheme mirrors the window but this appears to be just Mastodon software, though it was among other random logs from my own instance and other known and safe sites.

I was going try using Wireshark to log network connections when i entered in useless credentials like 12345 but I mistakenly closed the Sengi electron application when closing down all other stuff to make a cleaner log. I'll keep an eye out for this login screen again and Wireshark a connection on that login page as best I can, this may take weeks or months until I get a new spawn.

I not sure what exactly this is, but I fear the security implications that it may be a phishing attempt. I get that this will be extremely difficult for you to replicate, if not impossible, since I myself have only seen it maybe four times at random.

**Comment by NicolasConstant** [comment]
That's weird, and indeed it's not coming from Sengi; seems like a fishing attempt indeed. 
Since I've never seen such behavior myself, could it come from the tooling you're using to package the app? Maybe try using the webapp for some time with an up-to-date browser to see if it happen too?

**Comment by Salastil** [comment]
The tooling is nativefier: https://github.com/nativefier/nativefier which is just an electron wrapper using Chromium. The versioning behind my specific wrapped Sengi is nativefier 47.0.0 https://github.com/nativefier/nativefier/commit/567fede701ff8f0f235c472f5b6bb9989b5d45a3 
_Bump default Electron to 18.0.3 (from 16.2.2)_  

This would have the wrap job placed to occur sometime in or slightly after April 2022, so the various components of electron and chromium wouldn't be excessively obsolete, particularly since I run Arch so the Chromium package would also have been current at the time. Plus nativefier wrapped applications start bitching at about 6 months that its out of date so they never tend to get too old. 

Also, I don't mean to imply that this login screen is a function or feature of Sengi, I suspect that as the Federated feed scrolls by its making a connection to some random instance to load media and in the process this instance has some sort of login prompt when the media is accessed. Next time I encounter it, maybe in a few months, I'll try wiresharking the connection and see what instance it leads to. I've never encountered this spawn while I was at the device, usually it happens when I'm away for 8-12 hours.

**Comment by Salastil** [comment]
![1670083736](https://user-images.githubusercontent.com/46979341/205451637-dff32d81-a7e4-4d18-a233-5bcaa2df610b.png)
Had it pop up again, nothing showed in the developer tools when I tried logging in with fake credentials, nothing of note in the console or network tab. Probably because it's a spawned window. Once again it spawned when I was away for 8 hours or more and the Federated feed was allowed to scroll.  Next time I'm gonna Wireshark and see where it tries connecting to. 

I guess I'll be back next quarter.

**Comment by NicolasConstant** [comment]
That's really weird. 😐 
I hope we'll end getting a lead on this strange behavior.

**Comment by Salastil** [comment]
I'm fairly positive I figured out the cause, and I also believe its not derived from a singular source. I just happen to be present when it spawned so I was able to stop the Federated Timeline scrolling to a specific dozen I could inspect. This allowed me to spawn the prompt several times as I scrolled back and forth. I ran wireshark when I entered credentials and it led me to 35.196.127.177 which looks to be a generic Wordpress site, checking the DNS request done at the same time lead to https://poundofground.wpengine.com/ which redirects to https://www.poundofground.com/ so I'm fairly certain this was the offending site. Scrolling through the Federated feed I find an embed card from the same site. 

![1672506768](https://user-images.githubusercontent.com/46979341/210151012-2daf8ff3-c9aa-499e-94b7-0e025c25791c.png)
The image from the embed is on a separate site.
https://poundofground2.wpengine.com/wp-content/uploads/2021/04/POG-Homepage-Image2-1.jpg

`wget https://poundofground2.wpengine.com/wp-content/uploads/2021/04/POG-Homepage-Image2-1.jpg                         
--2022-12-31 12:07:57--  https://poundofground2.wpengine.com/wp-content/uploads/2021/04/POG-Homepage-Image2-1.jpg
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving poundofground2.wpengine.com (poundofground2.wpengine.com)... 35.196.127.177
Connecting to poundofground2.wpengine.com (poundofground2.wpengine.com)|35.196.127.177|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
`
When you go to this image via browser you get presented with a login prompt. So my theory is, whenever it hits a 401 request it spawns this dialog box to log in. I'm going to presume that this is a result of me wrapping it via nativefier. I have no idea how this scenario is handled per browser, checking it with Brave Browser throws an error in the console saying it failed to load resource because it responded with 401 but does not provide a login prompt. I think it is safe to say this is electron jank rather than anything inherit to Sengi, nor does it seem to be malicious, though it could be a vector by bad actors if someone wanted to run a phishing experiment on an infinitesimally small crowd that has the exact same setup that I do.

**Comment by NicolasConstant** [comment]
Oh I see. It's also linked to Pleroma since by default it doesn't cache content (you could set this cache functionality on your instance to prevent this behavior on your setup). 

Thanks for prospecting!
