### ISSUE TITLE
HTTP 400 Bad Request response when triggering (empty) auto-complete

### ISSUE THREAD

**Issue by capi** [NicolasConstant/sengi#452]
When creating a toot, as soon as `@` or `#` is entered, a 400 Bad Request error is shown, since apparently the search API is already triggered with the still empty search string.

![image](https://user-images.githubusercontent.com/254852/198831047-746ac724-293f-44b8-afd2-97085c6bf476.png)

**Comment by tux19** [comment]
This happens to me as well (https://tux.social)
