### ISSUE TITLE
Is the posting language of a mastodon profile respected?

### ISSUE THREAD

**Issue by ResilienceEconomist** [NicolasConstant/sengi#454]
Have been reviewing Sengi and from what I have seen it would be my preferred multi-account client. Good work, Nicolas!

One question I have, though: I am using two Mastodon accounts, each set to a different posting language.

When I add accounts to Sengi, will this setting be respected? Or more precisely, will the toots I send from within Sengi be marked as being in the posting language set for the respective account?

Many thanks!

**Comment by NicolasConstant** [comment]
sorry for not answering earlier, currently Sengi doesn't provide any language with the statuses. But in next release you'll be able to set languages in the app and it will be used in posting / translation.
