### ISSUE TITLE
[Feature Request] Ability to expand all CW posts by default

### ISSUE THREAD

**Issue by stormwulfren** [NicolasConstant/sengi#459]
For my usecase, it would be nice to be able to have all CW posts visible by default. For my use case, I'm an artist, and the timelines I frequent are mostly art, which most people, courteously CW the content. But given the sheer volume, I literally can't click on every single post to reveal the artwork. I'd much rather just have Sengi running on another monitor, just ticking away with an ambient feed.

**Comment by NicolasConstant** [comment]
Maybe expand fit better indeed, thanks for the idea!

**Comment by NicolasConstant** [comment]
will be fixed in next release!
