### ISSUE TITLE
Adjust font, size etc

### ISSUE THREAD

**Issue by audunmb** [NicolasConstant/sengi#463]
I find the text a bit small to read. An option to adjust font, line height, font size etc would be nice.

**Comment by NicolasConstant** [comment]
duplicate of #222 
(but you can also zoom in/out in the Electron build or in the browser if you want)

**Comment by ejheil** [comment]
@NicolasConstant  as noted in #222 the option to increase font size does not exist in the "view" menu of the Mac build.  Is there a workaround?

**Comment by NicolasConstant** [comment]
You could use the web version, but I'll have a look (when finding the time) why this option doesn't show up on Mac.

Also, please participate on the other issue since this one is a duplicate.
