### ISSUE TITLE
Official builds for Linux do not work out of the box

### ISSUE THREAD

**Issue by BatchDrake** [NicolasConstant/sengi#465]
Hi,

I am running a Debian Sid at home. Both the AppImage and the .deb builds fail with the following error:

```
% sengi
[868315:1111/095042.471921:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  sengi
```

I see a black window showing up, right before this error is displayed in the terminal and closing. This is most likely an Electron issue (https://github.com/Automattic/simplenote-electron/issues/3044#issuecomment-979289305, https://github.com/Automattic/simplenote-electron/issues/3096) and fortunately the workaround of passing `--no-sandbox` works (I am currently using it and everything works seamlessly).

However, I am not sure about the security implications of this trick. Maybe there's something that can be done at JavaScript level? (e.g. disabling the GPU until this is fixed?)

Cheers,

**Comment by ACalleros** [comment]
I am having the same issue with Manjaro Linux. I installed Sengi from the AUR and it wont open. After running sengi from the console I get this error: 

```
sengi                       
Gtk-Message: 10:53:27.687: Failed to load module "appmenu-gtk-module"
[22949:1116/105329.951230:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[1]    22949 trace trap (core dumped)  sengi
```

**Comment by markmandel** [comment]
Same here on Debian testing, nvidia driver installed.

```
➜  Downloads sengi

(sengi:12573): Gtk-WARNING **: 11:19:38.464: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
[12573:1120/111939.260155:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
[1]    12573 trace trap  sengi
```

**Comment by ryanayoung** [comment]
same issue on EndeavourOS(Arch)

**Comment by StarWitch** [comment]
Same issue here, and the `--no-sandbox` trick does indeed work. This is on a machine with an NVIDIA 1080 GTX, running the latest 525 drivers.

**Comment by TheTechnician27** [comment]
Can confirm this issue is still present for me on Manjaro.

```
[18489:0125/135526.227854:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  sengi
```

`--no-sandbox` worked for me too.

GPU is a GTX 1070 with video-nvidia as my driver.

**Comment by FlitPix** [comment]
Same issue here on Mint 21.1, GeForce GTX 1050 Ti:
```
$ sengi 
[99537:0127/205616.246854:FATAL:gpu_data_manager_impl_private.cc(442)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```
As aforementioned, the `--no-sandbox` flag fixes the issue.

**Comment by Animaly0** [comment]
Same issue on Arch and --no-sandbox did the trick

**Comment by NicolasConstant** [comment]
It seems the last build fixed it: https://github.com/NicolasConstant/sengi-electron/releases/tag/v1.5.5
