### ISSUE TITLE
Feature Request - Follow Hashtag

### ISSUE THREAD

**Issue by projectdp** [NicolasConstant/sengi#470]
[@sengi_app@mastodon.social](https://mastodon.social/@sengi_app) asked me to file an issue for a FR so here I am. 😄 

Follow Hashtag:
I noticed in the Mastodon webapp that there is a feature to follow hashtags. I had been using this to follow the various hashtags I'm interested in. I think the way it works is you follow the hashtag and it shows up in your home timeline. I know you can "add column" in Sengi but this isn't the same as it doesn't "follow" the hashtag, instead it has a column view of the hashtag in question.

Example from the Mastodon webapp:
![image](https://user-images.githubusercontent.com/1954180/201794433-4f9e2634-f8f8-497d-92d9-33f71fdedb3e.png)

Follow Hashtag-to-List:
Bonus points if you could select which List(s) to send the hashtag to. That would be an improvement over what is in the native Mastodon webapp, and would go a long way to curate the views you have. For instance if you wanted to store a set of related hashtags into a List you could select a dropdown and choose one or many Lists to assign the hashtag or user to. The default action could be to simply follow the hashtag.

Thanks for your work on this, good job!

**Comment by Kogimat** [comment]
Would it be a separate/distinct feature request to ask that the ability to aggregate multiple hashtags into a single column  or is it alright to add that as a part of this  one?

**Comment by NicolasConstant** [comment]
Yes that would be a different feature indeed. We already have an issue about it too: #333

**Comment by Kogimat** [comment]
I'm sorry, I tried checking to see if there already was an issue and.. i must have just failed my search check. Thanks!

**Comment by expertmanofficial** [comment]
I support this feature, we need it seriously!
