### ISSUE TITLE
Missing bookmark button for 4.0 Mastodon instances

### ISSUE THREAD

**Issue by tfardet** [NicolasConstant/sengi#479]
I have lost the bookmark button for the account I use/manage on instance that upgraded to Mastodon 4.0.
I'm not 100% whether this is the reason, but it's the only common point I found between these accounts.
The bookmark button is still there on my accounts on 3.5.3

**Comment by NicolasConstant** [comment]
It should have been fixed on the version published yesterday: 1.1.6, can you check what version you're using?

**Comment by tfardet** [comment]
Ah, yes, FSFE is still on 1.1.5, will ask them if they can update, sorry for the nosie
