### ISSUE TITLE
Possible server configuration error (social.vivaldi.net) on profile lookups

### ISSUE THREAD

**Issue by RedSnt** [NicolasConstant/sengi#482]
Hi, hello, sorry to bother you (again) with this problem. I mentioned on Mastodon how I was having problems looking up profiles on the social.vivaldi.net timeline while using Sengi, [so I asked on the Vivaldi forum](https://forum.vivaldi.net/topic/81044/social-graph-profile-hidden-using-desktop-clients/3#2) to see if someone a lot smarter than me could figure something out, and they (Pathduck) did some API lookups from the Vivaldi Social instance and noticed some irregularities, like how Sengi would try and look up profile data from "vivaldi.net" instead of "social.vivaldi.net".  

I haven't been able to reproduce the profile lookup problem using other clients like [TheDesk](https://app.thedesk.top/view/en/index.html) and [Hyperspace](https://hyperspaceapp.herokuapp.com/#/home), so I'm a bit perplexed whether this is a server configuration problem on Vivaldi Social's side or if it's how Sengi looks up profiles.

**Comment by NicolasConstant** [comment]
According to Pathduck, here are the results of the search requests: 

``` shell
$ curl -H "authorization: Bearer xxx" "https://social.vivaldi.net/api/v2/search?q=@pathduck@social.vivaldi.net&resolve=true"
{"error":"Remote data could not be fetched"}

$ curl -H "authorization: Bearer xxx" "https://social.vivaldi.net/api/v2/search?q=@pathduck@vivaldi.xxx&resolve=true"
{"accounts":[{"id":"109348563552594074","username":"Pathduck","acct":"Pathduck","display_name":"Pathduck","locked":false,"bot":false,"discoverable":false,"group":false,"created_at":"2022-11-15T00:00:00.000Z","note":"","url":"https://social.vivaldi.net/@Pathduck","avatar":"https://social-cdn.vivaldi.net/system/accounts/avatars/109/348/563/552/594/074/original/f07c39c74d28ba8f.jpeg","avatar_static":"https://social-cdn.vivaldi.net/system/accounts/avatars/109/348/563/552/594/074/original/f07c39c74d28ba8f.jpeg","header":"https://social-cdn.vivaldi.net/system/accounts/headers/109/348/563/552/594/074/original/a22bb32f402d8c17.jpg","header_static":"https://social-cdn.vivaldi.net/system/accounts/headers/109/348/563/552/594/074/original/a22bb32f402d8c17.jpg","followers_count":5,"following_count":8,"statuses_count":7,"last_status_at":"2022-11-19","noindex":false,"emojis":[],"fields":[]}],"statuses":[],"hashtags":[]}
```

So the `@pathduck@social.vivaldi.net` search fails but the `@pathduck@vivaldi.net` succeed. Since the instance is hosted on the `social` subdomain, and that Sengi is also checking the account on the `social` subdomain, my guess is that there is also an issue on your instance configuration. 

It might work on other application because they don't do this search request (searching accounts is part of the magic that permit Sengi to be truly multi-accounts over multiple and distinct instances), but this request is legit and should normally work.

**Comment by RedSnt** [comment]
This issue has been solved and was most likely a config error like suggested. Thanks for your time and work 😊
