### ISSUE TITLE
Sensitive Media Handling

### ISSUE THREAD

**Issue by motoridersd** [NicolasConstant/sengi#483]
It seems Sengi doesn't respect the Instance setting for hiding sensitive media, nor does there seem to be an option to change the behavior in Sengi. Or maybe Sengi doesn't have a way to hide sensitive media?

For example, I have two instances added. Both have "Hide media marked as sensitive" selected, but Sengi shows all media marked sensitive without blurring/hiding.

**Comment by NicolasConstant** [comment]
Sengi should hide posts with CW, unless you changed the "Content-Warning Policies" settings in the app. Can you check you have those set to "None" and try again? If the issue is still here can you share a post that isn't working so that I can have a look to it?

**Comment by motoridersd** [comment]
Ah! I think I was confused by the description of the settings. I thought "None" meant that no CW policies would apply, so I had set it to "Hide all CWs" which I thought meant "Hide all content that has a warning". I set it to none and now I see the images being handled properly.

**Comment by NicolasConstant** [comment]
Yes the wording is misleading, it will be changed in the next version. "Hide CW" will remove any CW applied to the posts. Happy it fixed your issue!
