### ISSUE TITLE
Feature Request: Reorganizing accounts

### ISSUE THREAD

**Issue by MrEnigmaSr** [NicolasConstant/sengi#489]
Having multiple accounts is nice but it is a little disorganized.  In order to improve usability.... it would be ideal to be able to slide the icons for the accounts you've logged into along the side like in discord or other apps.
As it stands it appears as tho accounts are ALWAYS listed in the order they were added which could lead to disastrous cross-posting.
The only way to get icons in the order you want them is to add them in the order you want them.

**Comment by GrahamDo** [comment]
I'd like to add my +1 to this. It'd be REALLY nice to be able to drag the icons up and down on the sidebar.

**Comment by GaelicGrime** [comment]
Up/down arrows like the column side to side has become a favorite on my foray into Android apps recently.
Not entirely certain why that over drag bars.
Perhaps an option to pick your method of reorganizing accounts, and even columns could be considered as part of this milestone?

**Comment by NicolasConstant** [comment]
I'm not sure already how I'll doing it, but I might choose the easiest/quickest way tbh, so only one way to do it.
Feel free to open another issue after release to describe another way (if needed), it's FLOSS and contributions are welcome.

**Comment by NicolasConstant** [comment]
will be available in the next release. 🙂
