### ISSUE TITLE
Feature Request: Language Translation

### ISSUE THREAD

**Issue by MrEnigmaSr** [NicolasConstant/sengi#490]
I do not know how this would be accomplished but I strongly believe that translation is essential to international communication.  Not everyone speaks the same language.  Being able to make friends anywhere in the world is one of the best parts of this sort of application.   
I am unsure if or how this could be implemented ... as far as I am aware this could get computationally cumbersome and would typically need to be done as a service?  Maybe there is some solution I am unaware of.

For now I use google translate when I really want to know what people say.

**Comment by orangesunny** [comment]
I am thinking about adopting Sengi for myself, and I’m open to helping with some localization efforts personally.

Moreover, we at Weblate offer a solution that’s already boosting communities and making users happy for large numbers of projects: https://weblate.org/hosting/#libre. Let me know if I can help anyhow.

**Comment by NicolasConstant** [comment]
fixed in develop, will be available next release
