### ISSUE TITLE
Feature request: Allow selecting the language

### ISSUE THREAD

**Issue by rstub** [NicolasConstant/sengi#496]
In Mastodon's official web-app it is possible to select the language for  an individual toot. This would be a good addition for multilingual accounts.

**Comment by troed** [comment]
Just chiming in that this is a showstopper for more than a few of us bilinguals :) On one of my accounts I post 50% Swedish and 50% English. Let's just say that most English speakers aren't that good at Swedish ;)

**Comment by NicolasConstant** [comment]
It would be a nice addition indeed (and I'm a bilingual myself too!), unfortunately I don't have a lot of bandwidth currently.

But PR are welcome!

**Comment by Inrumpo** [comment]
This would be a very helpful feature.

For the time being: What language are my toots set to by default?

**Comment by NicolasConstant** [comment]
I don't really know: Sengi doesn't provide any value to the API (it's an optional parameter), so it depends on Mastodon/Pleroma/Other MastoAPI compatible software default behavior.

**Comment by NicolasConstant** [comment]
fixed in dev branch, will be available next release
