### ISSUE TITLE
Window dimensions aren't saved

### ISSUE THREAD

**Issue by AxelTerizaki** [NicolasConstant/sengi#502]
Hello :)

When the app starts, it defaults to a single column width, but when y ou have everal columns, you'll want to resize the window to properly display them all, like on Tweetdeck.

However, the app doesn't save those new window X / Y dimensions when closing it. When restarting it, it goes back to one column width dimensions, forcing the user to resize the window again to accomodate several columns.

It'd be nice if it could be saved to config.

Thanks in advance!

**Comment by rpetti** [comment]
To add to this, it also doesn't seem save the window position. I ended up adding some separate automation (using EventGhost) to force it into the position and dimensions I want at startup.

**Comment by NicolasConstant** [comment]
closing due to being related to the electron build
