### ISSUE TITLE
Feature Request-Hide Titlebar Under Windows

### ISSUE THREAD

**Issue by y0himba** [NicolasConstant/sengi#509]
I am not sure I have the terminology correct, so I apologize if this is a dupe. I would love to be able to hide Windows' ugly titlebar.  See attached photo. The purple(on my PC) bar above the column headers that contains the minimise, restore, and close buttons. 

![image](https://user-images.githubusercontent.com/11462603/205465453-2288180e-3939-401c-989b-6cf4d64c100d.png)

**Comment by NicolasConstant** [comment]
closing due to rehosting the Electron build in another repository
