### ISSUE TITLE
Create Toot With CMD+Enter on MacOS

### ISSUE THREAD

**Issue by rukshn** [NicolasConstant/sengi#515]
The shortcut key combo available in most websites is the ability to submit a comment or create a post is with CTRL/CMD + Enter.

It would be great to have this feature on Sengi as well to toot and reply to toots with the above shortcut keys.

**Comment by NicolasConstant** [comment]
This is already supported, can you try it again on your side?

**Comment by rukshn** [comment]
hi I just tried, yes on Mac OS it works with CTRL+Enter but in MacOS unlike Widows the CMD key is used to perform the functions of the CTRL button.

So in MacOS it should be CMD+Enter and on Windows it should be CTRL+Enter. Pressing CTRL+Enter on MacOS to submit a form is kind of an anti pattern IMO.

**Comment by NicolasConstant** [comment]
I see. Thanks for the insight!
