### ISSUE TITLE
[bug] V1 search API used, but deprecated and removed in Mastodon 3.0.0 and later

### ISSUE THREAD

**Issue by philpem** [NicolasConstant/sengi#526]
I tried to run a search for a hashtag in Sengi earlier. A "404" error appeared at the bottom of the search window, from my Mastodon instance.

From the endpoint URL it appears that Sengi is using the v1 search API, which has been deprecated and removed in Mastodon 3.0.0 and later:

https://docs.joinmastodon.org/methods/search/#v1

Sadly this won't work on most current Mastodon deployments, and needs to be updated to use the v2 search API.

**Comment by philpem** [comment]
This also happens if you click a notification in the Notifications pane:

```
Http failure response for https://digipres.club/api/v1/search?q=https://irrelevant.me.uk/users/robert/statuses/109530749135446914&resolve=true: 404 OK
```

**Comment by anantshri** [comment]
I think i might have a idea about this bug.

https://digipres.club/nodeinfo/2.0 says its hometown and version number is hometown version.

https://github.com/superseriousbusiness/gotosocial/issues/1069 gotosocial suffers from a simmilar issue where sengi looks for v1 coz it assumes version less the 2 is using v1 api.

Hope this RCA is right and is helpful here.

**Comment by floogulinc** [comment]
This is also an issue with pleroma/akkoma instances it seems.

**Comment by NicolasConstant** [comment]
What version of pleroma?

**Comment by floogulinc** [comment]
The instance I tested it on is running Akkoma 3.5.0-0-gd9508474b

**Comment by LiamPM5** [comment]
I figured I would ask this here to clutter up the issue list less, unless I absolutely need to open one for what I'm experiencing.

It appears that this issue is preventing me from joining certain Mastodon servers. I was wondering if there's an ETA on this fix or if there's any further information I could provide in a bug report to help

**Comment by NicolasConstant** [comment]
Didn't realized before, but this issue is already fixed in the current version of Sengi.
