### ISSUE TITLE
Allow me to adjust the maximum number of characters in a post / detect max characters supported by instance

### ISSUE THREAD

**Issue by GrahamDo** [NicolasConstant/sengi#531]
Sengi only allows 500 characters before splitting posts. But my instance (c.im) actually supports up to 5000. And I think most do, these days.

Either allow me to specify in settings what the maximum number of characters are in a post, or try and detect it from the server somehow.

**Comment by NicolasConstant** [comment]
It's already supported. 🙂
If the service disclose the length (like Pleroma) it will be detected automatically, if not, you can change it in the account's panel settings: 
![image](https://user-images.githubusercontent.com/5437247/208774739-0318b75c-317f-4d76-8260-f00e75db128a.png)

**Comment by GrahamDo** [comment]
Cool. Found it. Thank you! :-)
