### ISSUE TITLE
Windows size and position not remembered

### ISSUE THREAD

**Issue by Brier1104** [NicolasConstant/sengi#535]
When you close and re-opening Sengi, the size any position of the window reverts to the default single column view, centered on the desktop.

Sengi v1.2.0
Windows 11 Pro 22H2

**Comment by cfrauenberger** [comment]
Yes, please, same on mac - I really love the multicolumn format, but it's cumbersome to resize the window every time when I close and re-open it.

**Comment by NicolasConstant** [comment]
closing due to rehosting the Electron build in another repository
