### ISSUE TITLE
Its not working on Safari

### ISSUE THREAD

**Issue by M00nwreck** [NicolasConstant/sengi#548]
I have a MacBook Pro 15 inch mid 2017 using Ventura 13.1 and using Safari 16.2 . I rather use the online version instead of downloading anything into my Mac. The first time that I Added a New Account it showed my home mastodon column but immediately afterword there is nothing showing. I can see my @mastodon username and server on the top of the column but there is nothing underneath. 
<img width="384" alt="image" src="https://user-images.githubusercontent.com/98116610/211212543-fee1f544-c286-4afc-91cd-917e5c9eceb8.png">

**Comment by NicolasConstant** [comment]
Hi! 
Can you [open your browser console](https://balsamiq.com/support/faqs/browserconsole/#apple-safari), refresh the page and look if there is any error popping up?

**Comment by M00nwreck** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/98116610/211315200-c57d496c-706b-4674-ab18-8dcbd89305e8.png">

<img width="785" alt="image" src="https://user-images.githubusercontent.com/98116610/211315357-d46be3bf-b245-4871-9ef3-b93c14ab03fb.png">

**Comment by NicolasConstant** [comment]
Can you reset your settings (settings/Clear all local content) and retry? Maybe we'll get some more interesting info.
