### ISSUE TITLE
ability to add Notifications Column

### ISSUE THREAD

**Issue by wakest** [NicolasConstant/sengi#55]
this would seem like an obvious feature, just making sure its on the radar.

**Comment by NicolasConstant** [comment]
It is. :) 
In fact, it might be a column a bit more "special" than the other usual timelines, to centralize all notifications of all accounts in the same place (having x columns for x accounts wouldn't be very useful). It will also probably be accessible via a dedicated icon in the left bar. It should be the next step after polishing the write status/reply functionalities.

**Comment by wakest** [comment]
this issue was closed but I just tried to make a notification column and it didn't work, was there a decision on this?

**Comment by NicolasConstant** [comment]
Yes, notifications are parts of the user's account, and when having a new notification, your account's icon should display an orange animation. 

I guess some people might not like this behavior, so I will maybe provide an option to disable it and let people adding columns like we can see in MastodonUI. 
What do you think? Have you tested the current implementation?
