### ISSUE TITLE
[Feature request] Add HTTP/SOCKS5 proxy support

### ISSUE THREAD

**Issue by chenshaoju** [NicolasConstant/sengi#551]
Hi, Sorry for my English.

Can we add proxy functionality, such as support for HTTP/SOCKS5 proxy servers?

**Comment by rpetti** [comment]
Sengi uses Electron for the frontend, so I suspect you might be able to work around this by using the startup flags for proxy settings:
https://github.com/electron/electron/blob/main/docs/api/command-line-switches.md#--proxy-serveraddressport

**Comment by chenshaoju** [comment]
Thank you! 🎉
