### ISSUE TITLE
It'd be nice if columns had the account name/image on them

### ISSUE THREAD

**Issue by SittenSpynne** [NicolasConstant/sengi#560]
I have more than one account on the same instance and want columns for their notifications. So seeing the instance name in the column doesn't help me figure out which account is getting mentions. It'd be nice if the columns displayed the full account name and/or the account's icon so I could keep it straight.

**Comment by NicolasConstant** [comment]
It's already there. 😉
Open the settings and choose your preferred flavor:

![image](https://user-images.githubusercontent.com/5437247/217691641-1a2f86bc-e183-4e55-9c2f-a778d71dd723.png)

**Comment by SittenSpynne** [comment]
Ooops! Sorry I didn't see that!
