### ISSUE TITLE
Introduce output for a version command for Linux AppImage

### ISSUE THREAD

**Issue by sid-the-sloth** [NicolasConstant/sengi#567]
It would be very nice if the AppImage could be called with a `--version` argument and output (in bash) the version number.

Similar to how `VSCodium` does for its AppImage. That would make app maintenance on a Linux system way easier.

Example, bash terminal:

Input:

`sengi.AppImage --version`

Output:

`1.2.0`

Thank you!

**Comment by NicolasConstant** [comment]
closing due to rehosting the Electron build in another repository
