### ISSUE TITLE
latest 1.2.0 deb asset shows old version 1.1.4-1087

### ISSUE THREAD

**Issue by philclifford** [NicolasConstant/sengi#569]
apt info ~/Downloads/Sengi-1.2.0-linux.deb 
Package: sengi
Version: 1.1.4-1087

Is it 1.1.4 ?

**Comment by NicolasConstant** [comment]
yes and no, I have currently some issues with the CICD (I have a fix, but I just need some time to deploy it) that prevented me to release an up-to-date binary. 

But since the Electron build is only a wrapper to fetch the app remotely, you still running the latest version of Sengi.
