### ISSUE TITLE
Right click does nothing

### ISSUE THREAD

**Issue by stemy2** [NicolasConstant/sengi#581]
Hello,

In previous installations on Sengi, i used the right click to copy texts or open the toots in the browser, but now, it doesn't work anymore, i just have a context menu with the entry "empty".

**Comment by NicolasConstant** [comment]
closing due to issue being related to the electron build

**Comment by stemy2** [comment]
So...does it means that there's a "not electron" version ? Where is it ? Because the link you mentioned in this current repository is actually the electron version.

**Comment by NicolasConstant** [comment]
Yes, Sengi is a webapp, you can find it on the [project page](https://nicolasconstant.github.io/sengi/) or via the [docker build](https://github.com/NicolasConstant/sengi/blob/master/DOCKER.md).
