### ISSUE TITLE
Support for bookmarks in non Mastodon instances

### ISSUE THREAD

**Issue by uda** [NicolasConstant/sengi#583]
I have at least two instances that I can't use bookmarks with them, one runs Pleroma and the other runs Takahe, both support bookmarks on the backend (Bookmarks work properly with soapbox and Fedilab).

From what I can see the logic is based on a version number comparison, which both Takahe (0.9.0) and Pleroma (2.7.2) don't meet, yet both support it properly.

**Comment by NicolasConstant** [comment]
Yes, when I've added bookmark support, the endpoints for Mastodon and Pleroma was a bit different, hence the limitation. But as a pleroma user myself, I agree that's something that really need to be fixed.

**Comment by NicolasConstant** [comment]
will be available in next release!
