### ISSUE TITLE
Add “Title - account icon - username - domain name” to Timelines → header display

### ISSUE THREAD

**Issue by jmcken1** [NicolasConstant/sengi#589]
Presently, the options under Timelines → header display include “Title (domain.name)”, “Title (username@domain.name)”, “Title | account icon (domain.name)”, “Title | account icon”, and “Title”. I think it would be nice if we combined the two most informative options to create a new option, “Title | account icon (username@domain.name)”, making as easy as possible to tell at a glance which column is for which account.

**Comment by HamzaFarooqArif** [comment]
I want to work on this. Can I get this task assigned to me?

**Comment by NicolasConstant** [comment]
Sure, thanks!
