### ISSUE TITLE
Markup doesn't look good in polls with long texts sometimes

### ISSUE THREAD

**Issue by archydragon** [NicolasConstant/sengi#593]
Firefox 115.0.2, Windows

![image](https://github.com/NicolasConstant/sengi/assets/854777/a5426a00-3f41-4664-8872-1e6f232cdf47)

<summary>HTML code of the post, if it helps: https://pastebin.com/zcqHie7X

Edit: Github doesn't like HTML within `<details>`, so using external Pastebin.

**Comment by NicolasConstant** [comment]
Can you provide me a link to one of those problematic posts? 
I struggle to reproduce the issue on my side.

**Comment by archydragon** [comment]
The post shown on the screenshot is https://loud.computer/@virtulis/110749477723262428, however, in search window it displays fine (for now).
It didn't occur more than once, so, guess, can be closed if it's too hard to reproduce :)

**Comment by NicolasConstant** [comment]
Thanks! I boosted it with a testing account to see, didn't occur either.
Closing for now, but if you find a way to reproduce, please comment again. 🙂
