### ISSUE TITLE
Poor man's formatting with whitespaces is omitted when displaying toots

### ISSUE THREAD

**Issue by archydragon** [NicolasConstant/sengi#597]
Example: https://loud.computer/@archydragon/110785247958886743

In Mastodon web UI (and how it's expected to look like):
![image](https://github.com/NicolasConstant/sengi/assets/854777/e29c2ee3-c777-4132-a4ba-5ebd5f6184d2)

In Sengi:
![image](https://github.com/NicolasConstant/sengi/assets/854777/b61f868e-1210-46eb-87d1-5f9340aa1609)

I've submitted that toot using Sengi, so it's purely displaying issue.

**Comment by NicolasConstant** [comment]
will be available in next release!
