### ISSUE TITLE
invalid token, problems re-adding nth account from same instance

### ISSUE THREAD

**Issue by colognella** [NicolasConstant/sengi#623]
Hi, sorry if this might be a problem in front of the laptop (and if there's a better place for support)… long time ago I managed successfully having 4 accounts in Sengi, 3 of those from one instance (and I'm happy with it). 

Recently I had do change the password for one of these accounts externally. Sengi removed it subsequently. Now I try to re-connect it and have one failure after another. It's not the „multiple accounts from one instance“ thing I suppose, I read that Wiki article multiple times. I won't get to the point that another account is logged in, but I see the logged-in "new" account and - apparently - could authorize it.

After trying to do that, I receive 2 visible error messages as red overlays:

1) Account example@the.instance is already registered 
2) Der Zugriffstoken ist ungültig (invalid token) 

The columns are still there but won't load anything.

The console shows as follows: 
Step 1: Submit the instance, display the logged in (new, correct) account to authorize:

--> "The source list for Content Security Policy directive 'script-src' contains an invalid source: ''wasm-unsafe-eval''. It will be ignored."

Step 2: click "authorize"

--> multiple errors

GET https://the.instance/api/v1/scheduled_statuses 401
GET https://the.instance/api/v1/accounts/verify_credentials 401
GET https://the.instance/api/v1/notifications?limit=10&exclude_types[]=mention 401
GET https://the.instance/api/v2/search?q=@example@the.instance&resolve=true 401)
WebSocket connection to 'wss://the.instance/api/v1/streaming?access_token=XXXXX&stream=public:local' failed: Error during WebSocket handshake: Unexpected response code: 301

(and a lot more 401/301) 

I could connect/authorize the account to other apps like Tusky, and I can login without any problems on the browser. This looks like an API error, maybe something with the cache? But I cannot get to understand if it's Sengi or the instance's API. 

Any idea what's going on here? Thanks!

**Comment by NicolasConstant** [comment]
Usually Sengi doesn't remove accounts how's token has been invalidated, you should still see the avatar (or the place used by the avatar) and open the account panel with a right click on it, there remove the account, and try re-adding it after that.

**Comment by colognella** [comment]
ahhhhhhh … I see. Well, I did not see the "invisible" avatar. Dark mode, „black eagle on black background“ …  everything fine, thanks!

**Comment by NicolasConstant** [comment]
Great! Making the avatar emplacement more obvious is something I should do, it can be misleading indeed.
