### ISSUE TITLE
Stipping out domain.tld out of mentions when editing a reply

### ISSUE THREAD

**Issue by DarkOverord** [NicolasConstant/sengi#630]
Is as the title states

If replying to @\name@\domain.tld and I choose to edit that at a later time it strips out @\domain.tld, meaning if I reply to it again it as a thread stops mentioning the intended users

Below is as it edits on the instance's deck, and in Sengi
![image](https://github.com/NicolasConstant/sengi/assets/141354147/a003c93d-c75f-4e28-9888-4fbd902bc38f)
![image](https://github.com/NicolasConstant/sengi/assets/141354147/97085688-4820-45a8-998e-0d099a46cd05)

Windows 10, Firefox 121.0, Sengi 1.6.0

**Comment by NicolasConstant** [comment]
will be fixed in next release!
