### ISSUE TITLE
[macOS desktop app] Can't paste password in the authentication screen

### ISSUE THREAD

**Issue by jumoru** [NicolasConstant/sengi#89]
Current behavior:

Can't paste an email address and/or password in the respective fields in the authentication screen, neither by using command+v nor via right clicking and selecting paste. Moreover, right clicking into the fields doesn't work at all.

Expected behavior:

It should be possible to paste an email address and password in the respective fields in the authentication screen, either by using command+v or via right clicking and selecting paste.

Steps to reproduce:

- click on the "+" button to add a new account
- provide the account name
- authentication screen opens
- try pasting an email address and password in the respective fields

Sengi 0.7.0
macOS 10.14.4
Instance: mastodon.social

**Comment by NicolasConstant** [comment]
Wow this is odd. 

Does it work with the browser version you can find [here](https://nicolasconstant.github.io/sengi/)?
On the desktop app, can you open the console (Help/Toggle Developper Tools/Console) and try this workflow again and see if something pops-up? 

Thanks for helping making Sengi better!

**Comment by jumoru** [comment]
Yes, it works in the browser version.

Is there another way to open the console than you've described? The desktop app for Mac neither shows "Help" nor "View" like the Windows app shown on your website (see screenshot)

![Bildschirmfoto 2019-05-14 um 10 10 15](https://user-images.githubusercontent.com/27491477/57681953-0ae89300-7631-11e9-872e-9d11cb9171ab.png)

**Comment by jumoru** [comment]
I'm not sure 100% whether this article addresses the correct problem, but non-working copy/paste shortcuts and missing menu on macOS at least sounds a lot like what's going on in Sengi

https://www.codedmaster.com/2017/01/24/getting-electron-copy-paste-shortcuts-for-mac-builds/

**Comment by NicolasConstant** [comment]
Oh I see, according to your link, macOS needs a bit more work to make the menu appear and work properly. 
I'll have a look and will provide you a 0.7.1 version with this fix to see if it solves the issue.

**Comment by NicolasConstant** [comment]
I've added the copy/paste menu to Sengi, you can find it [here](https://github.com/NicolasConstant/sengi/releases/download/0.7.1/Sengi-0.7.1-mac.dmg). 
I hope it will solve your issue. :)

**Comment by jumoru** [comment]
It's working now, thank you for the quick fix :)

**Comment by jumoru** [comment]
Addendum: I’ve just seen that it’s no longer possible to quit (command+q) Sengi. You probably have to add this to the menu as well.

**Comment by NicolasConstant** [comment]
And here is [another one](https://github.com/NicolasConstant/sengi/releases/download/0.7.2/Sengi-0.7.2-mac.dmg)!
You should now have the quit command, and also the other menu that wasn't displaying before. :)

**Comment by jumoru** [comment]
Thanks :) I'm now seeing the "View" and "Help" menu as well as an option to close the window (command+w). What I've meant however is the option to close/quit the app such that it's no longer running in the background (command+q). I'm really sorry if I wasn't clear enough about that.

**Comment by NicolasConstant** [comment]
Oh my bad, on Windows those two have the same behavior (killing the process). 
This last [release](https://github.com/NicolasConstant/sengi/releases/download/0.7.3/Sengi-0.7.3-mac.dmg) has the two commands. :)

**Comment by jumoru** [comment]
That's true, Windows and macOS indeed differ with respect to what closing the window does. From my point of view everything works as expected now, thank your for all the fixes :)
