### ISSUE TITLE
Weird missing post butons all the sudden

### ISSUE THREAD

**Issue by wakest** [NicolasConstant/sengi#98]
not sure whats up with this, just loaded Sengi again in Firefox on macOS and this happened. refreshed a few times and that didn't fix it. 
<img width="328" alt="Screen Shot 2019-05-17 at 10 28 31 PM" src="https://user-images.githubusercontent.com/7890201/57963517-40bc9e80-78f3-11e9-89d8-b808dc86f940.png">

**Comment by NicolasConstant** [comment]
Oh this is strange. I was pushing 0.8.0 this night, maybe it has break for an instant the online version? 
If it still here, can you look to the console (right-click/inspect/console) to see if something pops out?

**Comment by wakest** [comment]
just loaded Sengi and this happened again. Newest version of Firefox on newest version of macOS. 

I clicked this post in Sengi and loaded console and copied what it said to the file attached
[console.txt](https://github.com/NicolasConstant/sengi/files/3243300/console.txt)
.

**Comment by NicolasConstant** [comment]
Thanks!
It seems there is an issue with the lib ionicons, strangely I can't reproduce it on Firefox + Win10. The good news is that I was on the way to remove this lib for homogeneity,  so it should fix automatically this issue. :)

I will release a quick patch (0.9.1) to fix this.

**Comment by NicolasConstant** [comment]
0.9.1 is out! It should fix this issue. :)
